import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ParticlesComponent from "@/components/Particles";
import CursorEffect from "@/components/CursorEffect";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <div className="cursor-dot"></div>
        <div className="cursor-outline"></div>
        <CursorEffect/>
        <Header />
        {children}
        <ParticlesComponent/>
      </body>
    </html>
  );
}
